### PR TITLE
add beforeSend parameter to allow modification of xhr

### PR DESCRIPTION
**Pull request by magibney**
e.g., for adding authentication params, etc.

### CODE REVIEW

**Comment by jrochkind** [comment]
Thanks! Makes sense to me. Travis seems to be failing for some other reason, I'll look into it.

**Comment by jrochkind** [comment]
Can you add some brief docs in comments at the top of the js file revealing the existence of the new feature and an example of use?

**Comment by magibney** [comment]
Absolutely. Will re-submit PR soon. Thanks!

**Comment by jrochkind** [comment]
perfect, thanks. There's no tests for JS, but you've used this fork in your project succesfully? Works fine if beforeSend isn't set too? I guess it'd just send null to the jquery ajax, which should be fine. 

I'll try to get a release out soon, wanna fix some lingering minor issues in a patch release first if possible.

**Comment by magibney** [comment]
Yes, I can confirm that with leaving beforeSend undefined, it sends the request just as it used to, so should be backward-compatible.

**Pull request merged**
