### PR TITLE
Issue-41: Set up github actions.

### PR DESCRIPTION
**Pull request by dkinzer**
REF #41

* Removes .travis.yml config
* Adds equivalent github actions config.

### CODE REVIEW

**Comment by jrochkind** [comment]
Nice, thank you! Do we have a way to see if it works before we merge it? Could you merge it into your fork and demonstrate it working in your fork? 

Also can you replace travis badge in README with appropriage badge for github-actions?

**Comment by dkinzer** [comment]
@jrochkind I replaced the triavis ci badge with the GitHub version.

Also, I don't know how to test this without first merging it.  Maybe you can enable something in the Actions tab (I don't know)?

**Comment by jrochkind** [comment]
Hm, what if you try merging into master in your own tullibraries fork, so we can see it run (and hopefully pass?) on that repo?

**Comment by dkinzer** [comment]
Sure I could try that.

**Comment by dkinzer** [comment]
Good call.  Seems like it needs some more work: https://github.com/tulibraries/bento_search/actions/runs/958952668 

I'll revisit later:

**Comment by jrochkind** [comment]
Nice! just taking a sample of some of the error messages...

ruby 1.9.3 is apparently too old to install! I don't see any reason for bento_search not to just drop that. it's OLD. 

That might be true for ruby 2.2 and 2.3 too! We could drop old rubies. 

But it's more mysterious why eg 2.5.1 and rails 5.2.0 failed... "Error: the operation was cancelled" -- what? I'm not sure what's going on!

**Comment by dkinzer** [comment]
OK, this is working now... was forced to pin nokogiri and sqlite also had to fix one test.

**Comment by jrochkind** [comment]
Sweet, good job. 

The pinning nokogiri seems a bit odd to me; do you know what version of nokogiri it was ending up using before?

It's actually changing the requirements of bento_search, before it worked with any nokogiri, now it requires a nokogiri greater than 1.10. I guess that's okay, maybe we'll just do a major release of bento_search anyway?

With that in mind too, can you also update the README that says what versions of ruby/rails it works with, to match what is now actually being tested with? Currently says "Works with Rails 3.x, 4.x, or 5.0. ruby 1.9.3+", based on what you are actually testing with, I think that's actually "Works with Rails 5.x and ruby 2.3+" (although we aren't actually testing with recent rubies like 2.6, 2.7 or 3.0, which ideally we would be, but one step at a time!)

**Comment by dkinzer** [comment]
It was ending up on the latest version of nokogiri (1.11.7).  I guess it would be good to try and fix the Nokogiri issue.  Perhaps it's just a test issue more than a true incompatibility.

**Comment by jrochkind** [comment]
Hm. If the gemspec with unconstrained nokogiri was still ending up on the latest nokogiri... Ah, I see, now you are *preventing* the latest version of nokogiri, requiring exactly `1.10.x`.  

Yeah, that's not great. If we really want to prevent 1.11, we should do something more like `">= 1.0", "< 1.11"` or something, to allow any 1.x less than 1.11, instead of insisting only on 1.10. 

The problem with that (or with what you are doing now) is if you set it and forget it, you have a bento_search which is refusing to use new nokogiris forever. They release security patches in nokogori (it's happened before), bento_search is going to prevent an app from using that new release, it's saying "No, you aren't allowed to use nokogiri 1.12 or 1.13 or anything after 1.10".  I guess maybe that's okay if you remember to come back and fix it for real later, but to me it's asking for trouble. 

I dunno, if you were bento_search maintainer (and you might be soon :) ), what do you think should be done? Is that ok?

**Comment by jrochkind** [comment]
It might be that latest nokogiri doesn't work with the verisons of ruby we are still testing with, which are still pretty old and no-longer-supported rubies I think!

**Comment by dkinzer** [comment]
Yeah, actually I think latest versions might require no updates at all.

**Comment by dkinzer** [comment]
@jrochkind I've tried limiting it to those latest version and it's still failing a test.  I don't know what the test is trying to do so I don't know if the issue is the test or that it's actually flagging a real bug.

**Comment by jrochkind** [comment]
oh failing one test is an advance over not running at all! I can try to find some time to take a look! 

Possibly we should merge this in now anyway, to work on it here?

**Comment by jrochkind** [comment]
This run was all green though! https://github.com/tulibraries/bento_search/actions/runs/964967980

Hmm, I wonder what changed!

**Comment by dkinzer** [comment]
Yeah, nokogiri is still pinned in that run.  But, I thought you said you'd rather not do that.

**Comment by jrochkind** [comment]
Ah, right!   Yeah, people need to be able to use the most recent nokogiri. 

OK, so something in nokogiri behavior has changed to make that test fail. Possibly it's even a bug in nokogiri for us to report; and/or to work around to make the test pass -- it might just be something that needs to be changed in the test itself, or might actually represent something broken in the gem with the new version of nokogiri. 

I'll try to find time to debug it, and of course you are welcome to try too! 

I think this is part of updating bento_search so it'll work with modern setup, nobody wants to be stuck on an old version of nokogiri!

**Comment by dkinzer** [comment]
I know this  is purely anecdotal, but we're on the latest version of nokogiri and we have not noticed any issues.

**Comment by jrochkind** [comment]
OK, just looking at the failing test and the line that raises...

The test is trying to validate some Atom results that bento_search produces, validated against an Atom XSD schema. 

In nokogiri 1.11.7, trying to load the schema in with `schema = Nokogiri::XML::Schema.from_document( schema_xml )`...

raises `Nokogiri::XML::SyntaxError: 237:0: ERROR: attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.`

In nokogiri 1.10. it does not. 

I am going to figure out where I got this XSD from, reproduce a simple example, and perhaps report to nokogiri listserv and see what they say.

**Comment by jrochkind** [comment]
I'm not sure where I got the XSD document from... it's quite possible it really is illegal in some way? Atom seems to be kind of abandonware as a standard, and it's hard to find an XSD anywhere that isn't internet archive. (an XSD is not included in the official standards document). 

We could just eliminate that part of the test, stop testing that the Atom returned by some part of bento_search validates to an XSD?

**Comment by jrochkind** [comment]
I actually think I fixed the .xsd, but running locally I get an error involving celluloid too. 

Celluloid is only used by the deprecated MultiSearcher class (from README: "The previous MultiSearcher class is now deprecated, ConcurrentSearcher is the replacement, and will likely work as a drop-in replacement.") -- so I think it's probably just time to drop that deprecated class, and figure the next release will be a bento_search 2.x?

I'll make some PR's and merge them myself -- if you then rebase on master, you might find your tests are passing, we'll see!

**Comment by jrochkind** [comment]
Oh wait, I was wrong, I didn't fix the .xsd. :(

**Comment by jrochkind** [comment]
OK, so there's a feature in bento_search, which I assume you don't even use @dkinzer , to generate an Atom feed of results. 

One of the tests for it validates it against an Atom XML Schema (.xsd) file.  New versions of nokogiri (or libxml?) have made this code stop working and I've been unable to figure out how to fix it; it's got something to do with importing/resolving externally referenced xsd's from the atom xsd. 

But I think probably just removing that test is fine, it was ambitious and clever; there are still other tests of the atom feed feature, just not testing that it validates against an XSD. 

Any opinion @dkinzer ?

**Comment by dkinzer** [comment]
Hmmm ... is there a way we can verify the XML file itself?

**Comment by jrochkind** [comment]
Nevermind, I figured out a way to get it working! OK, in a few hours when I have everything merged, if you rebase your tests should pass.

**Comment by jrochkind** [comment]
@dkinzer I'm looking to merge this -- although might want to squash it into fewer commits first, there's a lot here!

Can you tell me about the `test/dummy/app/assets/config/manifest.js` file? Where did you get that file, and why?

**Comment by dkinzer** [comment]
@jrochkind that file was copied from `test/dummy/app/assets/javascripts/application.js ` to the new location.

**Pull request merged**
